### ISSUE TITLE
Assign unique ports for applications

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/haproxy#1]
I'm currently doing:

```
russell@kernhem:~/puppet/manifests/nodes$ grep 8080 mamirolle.pp 
      - "10.201.1.14:8083:8080"
      - "10.201.1.14:8082:8080"
      - "10.201.1.14:8081:8080"

```

I'm wanting to bind to the private internal port so that testing is easier, rather than using the internal docker bridge interface addresses.  It would be nice if ports were unique so that we could use the same in production as development.

**Comment by RussellMcOrmond** [comment]
@SaschaAdler ,

Close this if you wish.  Development and production can set up networks differently.  I think there are many advantages, including in development, to having each application image exposed so that it can be tested independent of HAProxy.  But if the private network is preferable for development, that can be kept.

**Comment by SaschaAdler** [comment]
I'll keep this open because it's probably a good idea. I'll keep tabs of what port each service is assigned to somewhere in this repo.

**Comment by SaschaAdler** [comment]
I'm making sure to do this in crkn-rcdr/Access-Platform; see https://github.com/crkn-rcdr/Access-Platform/blob/main/packages/env/README.md.
