### ISSUE TITLE
canadiana.org HTTPS errors

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/haproxy#2]
One unforeseen result of forcing HTTPS is that canadiana.org redirects have the following flow:

http://www.canadiana.org -> https://www.canadiana.org -> https://www.canadiana.ca

Since we don't have an up-to-date SSL cert for canadiana.org, this results in an SSL browser warning.

Solutions are either:
1. Get an up-to-date SSL cert for canadiana.org
2. Move the canadiana.org config somewhere where the redirect will happen to canadiana.ca before forcing HTTPS

**Comment by RussellMcOrmond** [comment]
3) Only redirect to SSL for *Canadiana.ca , and not other domains that we do special redirects within Apache.

**Comment by RussellMcOrmond** [comment]
This shouldn't have closed.  The config used in dev should probably match the type of thing we are doing in production.

**Comment by RussellMcOrmond** [comment]
We are using the following in production...

```
  # we'll uncomment this when we're ready for HTTPS always
  http-response set-header Strict-Transport-Security max-age=63072000
```

This means that at least temporarily anyone who went to the URL will be sent to HTTPS until this expires.  I can't figure out how to force it to clear earlier.

**Comment by RussellMcOrmond** [comment]
In production this is now changed to:

```
  # Only add header for https sites.
  http-response set-header Strict-Transport-Security max-age=63072000 if { ssl_fc }
```

This means the header is only added for SSL sites.  The header should be ignored by browsers when sent without SSL, but I seemed to have noticed a problem on Chrome.
